@startuml
package secretariavirtual <<Menús y tareas de inicialización: ensambla la aplicación>>
package tramites <<Trámites y tipos de expediente. Arquitectura propia: exento de las reglas>>
package system <<Función completa de la aplicación de la que no depende nadie>>
package subsystem <<Función completa de la aplicación de la que sí depende alguien>>

package base {
    package infrastructure <<Microarquitecturas independiente de la aplicación  >>
    package util <<Funciona básicas y pequeñas, restrigidas a una sola clase por funcionalidad>>
}

secretariavirtual --> system

system --> subsystem

tramites --> subsystem
tramites --> base

subsystem --> base

infrastructure --> util
@enduml
