pluginManagement {
    repositories {
        mavenLocal()
        mavenCentral() {
            content {
                excludeGroup 'com.axelor'
            }
        }
    }
}

dependencyResolutionManagement {
    repositories {
        mavenLocal()
        mavenCentral() {
            content {
                excludeGroup 'com.axelor'
            }
        }
        // Declare the Node.js download repository
        ivy {
            name = "Node.js"
            setUrl("https://nodejs.org/dist/")
            patternLayout {
                artifact("v[revision]/[artifact](-v[revision]-[classifier]).[ext]")
            }
            metadataSources {
                artifact()
            }
            content {
                includeModule("org.nodejs", "node")
            }
        }
    }
}

rootProject.name = 'secretaria-virtual'

