        @startuml

        state RECEPCION {
            state "ENTRADA_DATOS" as RECEPCION_ENTRADA_DATOS
        }

        state TRAMITACION {
            state "REVISIONEn claude" as TRAMITACION_REVISION
            state "ACEPTADO" as TRAMITACION_ACEPTADO
            state "RECHAZADO" as TRAMITACION_RECHAZADO
        }

        [*] --> RECEPCION_ENTRADA_DATOS
        ' RECEPCION_ENTRADA_DATOS --> <FASE>_<ESTADO DESTINO> : DELETE
        ' RECEPCION_ENTRADA_DATOS --> <FASE>_<ESTADO DESTINO> : PRESENTAR
        ' TRAMITACION_REVISION --> <FASE>_<ESTADO DESTINO> : SUBSANAR
        ' TRAMITACION_REVISION --> <FASE>_<ESTADO DESTINO> : ACEPTAR
        ' TRAMITACION_REVISION --> <FASE>_<ESTADO DESTINO> : RECHAZAR
        ' TRAMITACION_ACEPTADO --> <FASE>_<ESTADO DESTINO> : SUBSANAR
        ' TRAMITACION_RECHAZADO --> <FASE>_<ESTADO DESTINO> : SUBSANAR

        TRAMITACION_ACEPTADO : closed
        TRAMITACION_RECHAZADO : closed

        @enduml