@startuml

[*] --> ENTRADA_DATOS
ENTRADA_DATOS -> [*] : DELETE
ENTRADA_DATOS --> PENDIENTE_PRESENTACION : GUARDAR_DATOS
PENDIENTE_PRESENTACION --> ENTRADA_DATOS : BACK
PENDIENTE_PRESENTACION --> PENDIENTE_RESOLUCION : PRESENTAR
PENDIENTE_RESOLUCION --> ENTRADA_DATOS : RESOLVER[tipoResolucion=SUBSANAR_DATOS]
PENDIENTE_RESOLUCION --> ACEPTADO : RESOLVER[tipoResolucion=ACEPTAR]
PENDIENTE_RESOLUCION --> RECHAZADO : RESOLVER[tipoResolucion=RECHAZAR]

@enduml