@startuml

state SOLICITUD {
    state "DATOS_SOLICITUD" as SOLICITUD_DATOS_SOLICITUD
    state "PENDIENTE_FIRMA" as SOLICITUD_PENDIENTE_FIRMA
}

state REVISION {
    state "PENDIENTE_REVISION" as REVISION_PENDIENTE_REVISION
}

state RESOLUCION {
    state "PENDIENTE_FIRMA_DIRECTOR" as RESOLUCION_PENDIENTE_FIRMA_DIRECTOR
    state "ACEPTADA" as RESOLUCION_ACEPTADA
    state "RECHAZADA" as RESOLUCION_RECHAZADA
}

[*] --> SOLICITUD_DATOS_SOLICITUD
SOLICITUD_DATOS_SOLICITUD -> [*] : DELETE
SOLICITUD_DATOS_SOLICITUD --> SOLICITUD_PENDIENTE_FIRMA : CONTINUAR
SOLICITUD_PENDIENTE_FIRMA --> SOLICITUD_DATOS_SOLICITUD : VOLVER
SOLICITUD_PENDIENTE_FIRMA --> REVISION_PENDIENTE_REVISION : PRESENTAR
REVISION_PENDIENTE_REVISION --> RESOLUCION_PENDIENTE_FIRMA_DIRECTOR : CONTINUAR[sentidoRevision=ACEPTAR]
REVISION_PENDIENTE_REVISION --> RESOLUCION_PENDIENTE_FIRMA_DIRECTOR : CONTINUAR[sentidoRevision=RECHAZAR]
REVISION_PENDIENTE_REVISION --> SOLICITUD_DATOS_SOLICITUD : CONTINUAR[sentidoRevision=SUBSANAR]
RESOLUCION_PENDIENTE_FIRMA_DIRECTOR --> RESOLUCION_ACEPTADA : FIRMAR[sentidoRevision=ACEPTAR]
RESOLUCION_PENDIENTE_FIRMA_DIRECTOR --> RESOLUCION_RECHAZADA : FIRMAR[sentidoRevision=RECHAZAR]
RESOLUCION_PENDIENTE_FIRMA_DIRECTOR --> REVISION_PENDIENTE_REVISION : DEVOLVER

RESOLUCION_ACEPTADA : closed
RESOLUCION_RECHAZADA : closed

@enduml
