@startuml
[*] --> F_ENTRADA_DATOS
F_ENTRADA_DATOS --> F_ENTRADA_PENDIENTE_PRESENTACION_AUTOFIRMA : GUARDAR_DATOS
F_ENTRADA_PENDIENTE_PRESENTACION_AUTOFIRMA --> F_ENTRADA_DATOS : VOLVER_A_DATOS
F_ENTRADA_PENDIENTE_PRESENTACION_AUTOFIRMA --> F_SALIDA_PENDIENTE_RESOLUCION : PRESENTAR_AUTOFIRMA
F_SALIDA_PENDIENTE_RESOLUCION --> F_SALIDA_PENDIENTE_FIRMA_DIRECTOR : RESOLVER[tipoResolucion=RESPONDER]
F_SALIDA_PENDIENTE_RESOLUCION --> F_ENTRADA_DATOS : RESOLVER[tipoResolucion=SUBSANAR_DATOS]
F_SALIDA_PENDIENTE_FIRMA_DIRECTOR --> F_TERMINADO_RESPONDIDO : FIRMA_COMPLETADA\n(el director firma en el portafirmas)
F_TERMINADO_RESPONDIDO : closed
@enduml
