@startuml
Centro "1" -- "*" CursoAcademico
CursoAcademico "1" -- "*" FamiliaProfesional
FamiliaProfesional "1" -- "*" Nivel
Nivel "1" -- "*" Ciclo
Ciclo "1" -- "*" Curso

Curso "*" -- "*" Grupo
(Curso, Grupo) . CursoGrupo

Curso "*" -- "*" Modulo
(Curso, Modulo) . CursoModulo

Usuario "*" -- "*" CursoAcademico
(Usuario, CursoAcademico) . CursoAcademicoUsuario

Usuario "*" -- "*" CursoGrupo
(Usuario, CursoGrupo) . CursoGrupoUsuario

CursoAcademicoUsuario "1" -- "*" CursoGrupo

CursoAcademicoUsuario "*" -- "*" RolAcademico
(RolAcademico, CursoAcademico) . CursoAcademicoUsuarioRolAcademico

class Centro {
    administrador: Usuario
}

class CursoAcademico {
}

class FamiliaProfesional {
}

class Nivel {
}

class Ciclo {
}

class Curso {
}

class Grupo {
}

class Modulo {
}


class Usuario {
}

class CursoAcademicoUsuario {
}

class RolAcademico {
    tipo {
    Administrador,
    Profesor,
    Alumno,
    Administrativo,
    Conserje,
    Externo,
    Director,
    Secretario,
    JefeEstudios,
    Vicedirector,
    Vicesecretario,
    Delegado,
    Subdelegado,
    Tutor,
    JefeDepartamento}
}

class CursoGrupo {
    tutor1: Usuario,
    tutor2: Usuario
}
@enduml


