@startuml
Centro "1" -- "*" Cargo
Centro "1" -- "*" CursoAcademico

Usuario "*" -- "*" CursoAcademico
(Usuario, CursoAcademico) . CursoAcademicoUsuario

Cargo "*" -- "*" CursoAcademico
(Cargo, CursoAcademico) . CursoAcademicoCargo

CursoAcademicoUsuario "*" -- "*" Cargo
(CursoAcademicoUsuario, Cargo) . CursoAcademicoUsuarioCargo

class CursoAcademicoUsuario {
    tipoUsuario {Profesor,Alumno,Administrativo,Conserje,Externo}
}

class Cargo {
    tipoUsuario
    adminCentro
}

class CursoAcademico {
}

class CursoAcademicoUsuarioCargo {
}
@enduml

