INSERT INTO common_comunidad_autonoma (id, version, created_on, created_by, code, name) VALUES
    (nextval('common_comunidad_autonoma_seq'), 0, CURRENT_TIMESTAMP, 1, '01', 'Andalucía'),
    (nextval('common_comunidad_autonoma_seq'), 0, CURRENT_TIMESTAMP, 1, '02', 'Aragón'),
    (nextval('common_comunidad_autonoma_seq'), 0, CURRENT_TIMESTAMP, 1, '03', 'Asturias, Principado de'),
    (nextval('common_comunidad_autonoma_seq'), 0, CURRENT_TIMESTAMP, 1, '04', 'Balears, Illes'),
    (nextval('common_comunidad_autonoma_seq'), 0, CURRENT_TIMESTAMP, 1, '05', 'Canarias'),
    (nextval('common_comunidad_autonoma_seq'), 0, CURRENT_TIMESTAMP, 1, '06', 'Cantabria'),
    (nextval('common_comunidad_autonoma_seq'), 0, CURRENT_TIMESTAMP, 1, '07', 'Castilla y León'),
    (nextval('common_comunidad_autonoma_seq'), 0, CURRENT_TIMESTAMP, 1, '08', 'Castilla - La Mancha'),
    (nextval('common_comunidad_autonoma_seq'), 0, CURRENT_TIMESTAMP, 1, '09', 'Cataluña'),
    (nextval('common_comunidad_autonoma_seq'), 0, CURRENT_TIMESTAMP, 1, '10', 'Comunitat Valenciana'),
    (nextval('common_comunidad_autonoma_seq'), 0, CURRENT_TIMESTAMP, 1, '11', 'Extremadura'),
    (nextval('common_comunidad_autonoma_seq'), 0, CURRENT_TIMESTAMP, 1, '12', 'Galicia'),
    (nextval('common_comunidad_autonoma_seq'), 0, CURRENT_TIMESTAMP, 1, '13', 'Madrid, Comunidad de'),
    (nextval('common_comunidad_autonoma_seq'), 0, CURRENT_TIMESTAMP, 1, '14', 'Murcia, Región de'),
    (nextval('common_comunidad_autonoma_seq'), 0, CURRENT_TIMESTAMP, 1, '15', 'Navarra, Comunidad Foral de'),
    (nextval('common_comunidad_autonoma_seq'), 0, CURRENT_TIMESTAMP, 1, '16', 'País Vasco'),
    (nextval('common_comunidad_autonoma_seq'), 0, CURRENT_TIMESTAMP, 1, '17', 'Rioja, La'),
    (nextval('common_comunidad_autonoma_seq'), 0, CURRENT_TIMESTAMP, 1, '18', 'Ceuta'),
    (nextval('common_comunidad_autonoma_seq'), 0, CURRENT_TIMESTAMP, 1, '19', 'Melilla');



INSERT INTO common_provincia (id, version, created_on, created_by, code, name, comunidad_autonoma) VALUES
    (nextval('common_provincia_seq'), 0, CURRENT_TIMESTAMP, 1, '01', 'Araba/Álava', (SELECT id FROM common_comunidad_autonoma WHERE code = '16')),
    (nextval('common_provincia_seq'), 0, CURRENT_TIMESTAMP, 1, '02', 'Albacete', (SELECT id FROM common_comunidad_autonoma WHERE code = '08')),
    (nextval('common_provincia_seq'), 0, CURRENT_TIMESTAMP, 1, '03', 'Alicante/Alacant', (SELECT id FROM common_comunidad_autonoma WHERE code = '10')),
    (nextval('common_provincia_seq'), 0, CURRENT_TIMESTAMP, 1, '04', 'Almería', (SELECT id FROM common_comunidad_autonoma WHERE code = '01')),
    (nextval('common_provincia_seq'), 0, CURRENT_TIMESTAMP, 1, '05', 'Ávila', (SELECT id FROM common_comunidad_autonoma WHERE code = '07')),
    (nextval('common_provincia_seq'), 0, CURRENT_TIMESTAMP, 1, '06', 'Badajoz', (SELECT id FROM common_comunidad_autonoma WHERE code = '11')),
    (nextval('common_provincia_seq'), 0, CURRENT_TIMESTAMP, 1, '07', 'Balears, Illes', (SELECT id FROM common_comunidad_autonoma WHERE code = '04')),
    (nextval('common_provincia_seq'), 0, CURRENT_TIMESTAMP, 1, '08', 'Barcelona', (SELECT id FROM common_comunidad_autonoma WHERE code = '09')),
    (nextval('common_provincia_seq'), 0, CURRENT_TIMESTAMP, 1, '09', 'Burgos', (SELECT id FROM common_comunidad_autonoma WHERE code = '07')),
    (nextval('common_provincia_seq'), 0, CURRENT_TIMESTAMP, 1, '10', 'Cáceres', (SELECT id FROM common_comunidad_autonoma WHERE code = '11')),
    (nextval('common_provincia_seq'), 0, CURRENT_TIMESTAMP, 1, '11', 'Cádiz', (SELECT id FROM common_comunidad_autonoma WHERE code = '01')),
    (nextval('common_provincia_seq'), 0, CURRENT_TIMESTAMP, 1, '12', 'Castellón/Castelló', (SELECT id FROM common_comunidad_autonoma WHERE code = '10')),
    (nextval('common_provincia_seq'), 0, CURRENT_TIMESTAMP, 1, '13', 'Ciudad Real', (SELECT id FROM common_comunidad_autonoma WHERE code = '08')),
    (nextval('common_provincia_seq'), 0, CURRENT_TIMESTAMP, 1, '14', 'Córdoba', (SELECT id FROM common_comunidad_autonoma WHERE code = '01')),
    (nextval('common_provincia_seq'), 0, CURRENT_TIMESTAMP, 1, '15', 'Coruña, A', (SELECT id FROM common_comunidad_autonoma WHERE code = '12')),
    (nextval('common_provincia_seq'), 0, CURRENT_TIMESTAMP, 1, '16', 'Cuenca', (SELECT id FROM common_comunidad_autonoma WHERE code = '08')),
    (nextval('common_provincia_seq'), 0, CURRENT_TIMESTAMP, 1, '17', 'Girona', (SELECT id FROM common_comunidad_autonoma WHERE code = '09')),
    (nextval('common_provincia_seq'), 0, CURRENT_TIMESTAMP, 1, '18', 'Granada', (SELECT id FROM common_comunidad_autonoma WHERE code = '01')),
    (nextval('common_provincia_seq'), 0, CURRENT_TIMESTAMP, 1, '19', 'Guadalajara', (SELECT id FROM common_comunidad_autonoma WHERE code = '08')),
    (nextval('common_provincia_seq'), 0, CURRENT_TIMESTAMP, 1, '20', 'Gipuzkoa', (SELECT id FROM common_comunidad_autonoma WHERE code = '16')),
    (nextval('common_provincia_seq'), 0, CURRENT_TIMESTAMP, 1, '21', 'Huelva', (SELECT id FROM common_comunidad_autonoma WHERE code = '01')),
    (nextval('common_provincia_seq'), 0, CURRENT_TIMESTAMP, 1, '22', 'Huesca', (SELECT id FROM common_comunidad_autonoma WHERE code = '02')),
    (nextval('common_provincia_seq'), 0, CURRENT_TIMESTAMP, 1, '23', 'Jaén', (SELECT id FROM common_comunidad_autonoma WHERE code = '01')),
    (nextval('common_provincia_seq'), 0, CURRENT_TIMESTAMP, 1, '24', 'León', (SELECT id FROM common_comunidad_autonoma WHERE code = '07')),
    (nextval('common_provincia_seq'), 0, CURRENT_TIMESTAMP, 1, '25', 'Lleida', (SELECT id FROM common_comunidad_autonoma WHERE code = '09')),
    (nextval('common_provincia_seq'), 0, CURRENT_TIMESTAMP, 1, '26', 'Rioja, La', (SELECT id FROM common_comunidad_autonoma WHERE code = '17')),
    (nextval('common_provincia_seq'), 0, CURRENT_TIMESTAMP, 1, '27', 'Lugo', (SELECT id FROM common_comunidad_autonoma WHERE code = '12')),
    (nextval('common_provincia_seq'), 0, CURRENT_TIMESTAMP, 1, '28', 'Madrid', (SELECT id FROM common_comunidad_autonoma WHERE code = '13')),
    (nextval('common_provincia_seq'), 0, CURRENT_TIMESTAMP, 1, '29', 'Málaga', (SELECT id FROM common_comunidad_autonoma WHERE code = '01')),
    (nextval('common_provincia_seq'), 0, CURRENT_TIMESTAMP, 1, '30', 'Murcia', (SELECT id FROM common_comunidad_autonoma WHERE code = '14')),
    (nextval('common_provincia_seq'), 0, CURRENT_TIMESTAMP, 1, '31', 'Navarra', (SELECT id FROM common_comunidad_autonoma WHERE code = '15')),
    (nextval('common_provincia_seq'), 0, CURRENT_TIMESTAMP, 1, '32', 'Ourense', (SELECT id FROM common_comunidad_autonoma WHERE code = '12')),
    (nextval('common_provincia_seq'), 0, CURRENT_TIMESTAMP, 1, '33', 'Asturias', (SELECT id FROM common_comunidad_autonoma WHERE code = '03')),
    (nextval('common_provincia_seq'), 0, CURRENT_TIMESTAMP, 1, '34', 'Palencia', (SELECT id FROM common_comunidad_autonoma WHERE code = '07')),
    (nextval('common_provincia_seq'), 0, CURRENT_TIMESTAMP, 1, '35', 'Palmas, Las', (SELECT id FROM common_comunidad_autonoma WHERE code = '05')),
    (nextval('common_provincia_seq'), 0, CURRENT_TIMESTAMP, 1, '36', 'Pontevedra', (SELECT id FROM common_comunidad_autonoma WHERE code = '12')),
    (nextval('common_provincia_seq'), 0, CURRENT_TIMESTAMP, 1, '37', 'Salamanca', (SELECT id FROM common_comunidad_autonoma WHERE code = '07')),
    (nextval('common_provincia_seq'), 0, CURRENT_TIMESTAMP, 1, '38', 'Santa Cruz de Tenerife', (SELECT id FROM common_comunidad_autonoma WHERE code = '05')),
    (nextval('common_provincia_seq'), 0, CURRENT_TIMESTAMP, 1, '39', 'Cantabria', (SELECT id FROM common_comunidad_autonoma WHERE code = '06')),
    (nextval('common_provincia_seq'), 0, CURRENT_TIMESTAMP, 1, '40', 'Segovia', (SELECT id FROM common_comunidad_autonoma WHERE code = '07')),
    (nextval('common_provincia_seq'), 0, CURRENT_TIMESTAMP, 1, '41', 'Sevilla', (SELECT id FROM common_comunidad_autonoma WHERE code = '01')),
    (nextval('common_provincia_seq'), 0, CURRENT_TIMESTAMP, 1, '42', 'Soria', (SELECT id FROM common_comunidad_autonoma WHERE code = '07')),
    (nextval('common_provincia_seq'), 0, CURRENT_TIMESTAMP, 1, '43', 'Tarragona', (SELECT id FROM common_comunidad_autonoma WHERE code = '09')),
    (nextval('common_provincia_seq'), 0, CURRENT_TIMESTAMP, 1, '44', 'Teruel', (SELECT id FROM common_comunidad_autonoma WHERE code = '02')),
    (nextval('common_provincia_seq'), 0, CURRENT_TIMESTAMP, 1, '45', 'Toledo', (SELECT id FROM common_comunidad_autonoma WHERE code = '08')),
    (nextval('common_provincia_seq'), 0, CURRENT_TIMESTAMP, 1, '46', 'Valencia/Valéncia', (SELECT id FROM common_comunidad_autonoma WHERE code = '10')),
    (nextval('common_provincia_seq'), 0, CURRENT_TIMESTAMP, 1, '47', 'Valladolid', (SELECT id FROM common_comunidad_autonoma WHERE code = '07')),
    (nextval('common_provincia_seq'), 0, CURRENT_TIMESTAMP, 1, '48', 'Bizkaia', (SELECT id FROM common_comunidad_autonoma WHERE code = '16')),
    (nextval('common_provincia_seq'), 0, CURRENT_TIMESTAMP, 1, '49', 'Zamora', (SELECT id FROM common_comunidad_autonoma WHERE code = '07')),
    (nextval('common_provincia_seq'), 0, CURRENT_TIMESTAMP, 1, '50', 'Zaragoza', (SELECT id FROM common_comunidad_autonoma WHERE code = '02')),
    (nextval('common_provincia_seq'), 0, CURRENT_TIMESTAMP, 1, '51', 'Ceuta', (SELECT id FROM common_comunidad_autonoma WHERE code = '18')),
    (nextval('common_provincia_seq'), 0, CURRENT_TIMESTAMP, 1, '52', 'Melilla', (SELECT id FROM common_comunidad_autonoma WHERE code = '19'));
