INSERT INTO sistemaeducativo_familia_profesional (id, version, created_on, created_by, code, NAME) SELECT nextval('sistemaeducativo_familia_profesional_seq'), 0, CURRENT_TIMESTAMP, 1, 'FISICAS_DEPORTIVAS', 'Actividades Físicas y Deportivas' ;
INSERT INTO sistemaeducativo_familia_profesional (id, version, created_on, created_by, code, NAME) SELECT nextval('sistemaeducativo_familia_profesional_seq'), 0, CURRENT_TIMESTAMP, 1, '001', 'Administración y Gestión' ;
INSERT INTO sistemaeducativo_familia_profesional (id, version, created_on, created_by, code, NAME) SELECT nextval('sistemaeducativo_familia_profesional_seq'), 0, CURRENT_TIMESTAMP, 1, 'AGRARIA', 'Agraria' ;
INSERT INTO sistemaeducativo_familia_profesional (id, version, created_on, created_by, code, NAME) SELECT nextval('sistemaeducativo_familia_profesional_seq'), 0, CURRENT_TIMESTAMP, 1, 'GRAFICAS', 'Artes Gráficas' ;
INSERT INTO sistemaeducativo_familia_profesional (id, version, created_on, created_by, code, NAME) SELECT nextval('sistemaeducativo_familia_profesional_seq'), 0, CURRENT_TIMESTAMP, 1, '020', 'Comercio y Marketing' ;
INSERT INTO sistemaeducativo_familia_profesional (id, version, created_on, created_by, code, NAME) SELECT nextval('sistemaeducativo_familia_profesional_seq'), 0, CURRENT_TIMESTAMP, 1, 'EDIFICACION', 'Edificación y Obra Civil' ;
INSERT INTO sistemaeducativo_familia_profesional (id, version, created_on, created_by, code, NAME) SELECT nextval('sistemaeducativo_familia_profesional_seq'), 0, CURRENT_TIMESTAMP, 1, 'ELECTRICIDAD', 'Electricidad y Electrónica' ;
INSERT INTO sistemaeducativo_familia_profesional (id, version, created_on, created_by, code, NAME) SELECT nextval('sistemaeducativo_familia_profesional_seq'), 0, CURRENT_TIMESTAMP, 1, '129', 'Fabricación Mecánica' ;
INSERT INTO sistemaeducativo_familia_profesional (id, version, created_on, created_by, code, NAME) SELECT nextval('sistemaeducativo_familia_profesional_seq'), 0, CURRENT_TIMESTAMP, 1, '039', 'Hostelería y Turismo' ;
INSERT INTO sistemaeducativo_familia_profesional (id, version, created_on, created_by, code, NAME) SELECT nextval('sistemaeducativo_familia_profesional_seq'), 0, CURRENT_TIMESTAMP, 1, 'IMAGENPERSONAL', 'Imagen Personal' ;
INSERT INTO sistemaeducativo_familia_profesional (id, version, created_on, created_by, code, NAME) SELECT nextval('sistemaeducativo_familia_profesional_seq'), 0, CURRENT_TIMESTAMP, 1, 'IMAGENSONIDO', 'Imagen y Sonido' ;
INSERT INTO sistemaeducativo_familia_profesional (id, version, created_on, created_by, code, NAME) SELECT nextval('sistemaeducativo_familia_profesional_seq'), 0, CURRENT_TIMESTAMP, 1, 'INDUSTRIA_ALIMENTARIA', 'Industrias Alimentarias' ;
INSERT INTO sistemaeducativo_familia_profesional (id, version, created_on, created_by, code, NAME) SELECT nextval('sistemaeducativo_familia_profesional_seq'), 0, CURRENT_TIMESTAMP, 1, 'INDUSTRIA_EXTRACTIVA', 'Industrias Extractivas' ;
INSERT INTO sistemaeducativo_familia_profesional (id, version, created_on, created_by, code, NAME) SELECT nextval('sistemaeducativo_familia_profesional_seq'), 0, CURRENT_TIMESTAMP, 1, '190', 'Informática y Comunicaciones' ;
INSERT INTO sistemaeducativo_familia_profesional (id, version, created_on, created_by, code, NAME) SELECT nextval('sistemaeducativo_familia_profesional_seq'), 0, CURRENT_TIMESTAMP, 1, 'INSTALACION', 'Instalación y Mantenimiento' ;
INSERT INTO sistemaeducativo_familia_profesional (id, version, created_on, created_by, code, NAME) SELECT nextval('sistemaeducativo_familia_profesional_seq'), 0, CURRENT_TIMESTAMP, 1, 'MADERA', 'Madera, Mueble y Corcho' ;
INSERT INTO sistemaeducativo_familia_profesional (id, version, created_on, created_by, code, NAME) SELECT nextval('sistemaeducativo_familia_profesional_seq'), 0, CURRENT_TIMESTAMP, 1, 'MARITIMO', 'Marítimo - Pesquera' ;
INSERT INTO sistemaeducativo_familia_profesional (id, version, created_on, created_by, code, NAME) SELECT nextval('sistemaeducativo_familia_profesional_seq'), 0, CURRENT_TIMESTAMP, 1, 'QUIMICA', 'Química' ;
INSERT INTO sistemaeducativo_familia_profesional (id, version, created_on, created_by, code, NAME) SELECT nextval('sistemaeducativo_familia_profesional_seq'), 0, CURRENT_TIMESTAMP, 1, '061', 'Sanidad' ;
INSERT INTO sistemaeducativo_familia_profesional (id, version, created_on, created_by, code, NAME) SELECT nextval('sistemaeducativo_familia_profesional_seq'), 0, CURRENT_TIMESTAMP, 1, 'MEDIO_AMBIENTE', 'Seguridad y Medio Ambiente' ;
INSERT INTO sistemaeducativo_familia_profesional (id, version, created_on, created_by, code, NAME) SELECT nextval('sistemaeducativo_familia_profesional_seq'), 0, CURRENT_TIMESTAMP, 1, 'SOCIO_CULTURALES', 'Servicios Socioculturales y a la Comunidad' ;
INSERT INTO sistemaeducativo_familia_profesional (id, version, created_on, created_by, code, NAME) SELECT nextval('sistemaeducativo_familia_profesional_seq'), 0, CURRENT_TIMESTAMP, 1, 'TEXTIL', 'Textil, Confección y Piel' ;
INSERT INTO sistemaeducativo_familia_profesional (id, version, created_on, created_by, code, NAME) SELECT nextval('sistemaeducativo_familia_profesional_seq'), 0, CURRENT_TIMESTAMP, 1, 'TRANSPORTE', 'Transporte y Mantenimiento de Vehículos' ;
INSERT INTO sistemaeducativo_familia_profesional (id, version, created_on, created_by, code, NAME) SELECT nextval('sistemaeducativo_familia_profesional_seq'), 0, CURRENT_TIMESTAMP, 1, 'VIDRIO', 'Vidrio y Cerámica' ;
INSERT INTO sistemaeducativo_familia_profesional (id, version, created_on, created_by, code, NAME) SELECT nextval('sistemaeducativo_familia_profesional_seq'), 0, CURRENT_TIMESTAMP, 1, 'ARTES_GRAFICAS', 'Artes y Artesanías' ;
INSERT INTO sistemaeducativo_familia_profesional (id, version, created_on, created_by, code, NAME) SELECT nextval('sistemaeducativo_familia_profesional_seq'), 0, CURRENT_TIMESTAMP, 1, 'ENERGIA', 'Energía y Agua' ;


