@startuml

class Grupo {
  + nombre
  + curso
  + curso académico
  + centro
  + estado
  + fecha de cierre
}

enum EstadoGrupo {
  ABIERTO
  CERRADO
}

class ModuloGrupo {
  + módulo
}

class AlumnoGrupo {
  + alumno
  + nota media
}

class Nota {
  + valor
  + fecha de calificación
  + fecha de última modificación
}

Grupo --> EstadoGrupo
Grupo "1" *-- "0..*" ModuloGrupo : módulos
Grupo "1" *-- "0..*" AlumnoGrupo : alumnos
ModuloGrupo "1" *-- "0..*" Nota : notas
AlumnoGrupo "1" *-- "0..*" Nota : notas

@enduml
